---
abstract: 'Perl module to create AnyEvent timers from DateTime Events'
author:
  - 'Mark Hindess <soft-cpan@temporalanomaly.com>'
build_requires:
  English: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-DateTime
requires:
  AnyEvent: 0
  Carp: 0
  Class::Load: 0
  Scalar::Util: 0
resources:
  bugtracker: https://github.com/beanz/anyevent-datetime-perl/issues
  repository: git://github.com/beanz/anyevent-datetime-perl.git
version: 1.120710
